---
apiVersion: cassandra.cql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  sslMode: disable
  credentials:
    source: CassandraConnectionSecret
    connectionSecretRef:
      namespace: default
      name: db-conn
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  sslMode: disable
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: default
      name: db-conn

# docker run --rm -p 5432:5432  -e POSTGRES_PASSWORD=pass postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
stringData:
  username: postgres
  password: pass
  endpoint: localhost
  port: "5432"
---
apiVersion: cassandra.cql.crossplane.io/v1alpha1
kind: Keyspace
metadata:
  name: something
spec:
  forProvider: {}